# Generated by Django 5.0.14 on 2025-11-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_apiusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, default="openweathermap", max_length=64
                    ),
                ),
                ("endpoint", models.CharField(db_index=True, max_length=128)),
                ("status_code", models.IntegerField()),
                ("bytes", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ApiUsage",
        ),
        migrations.DeleteModel(
            name="Flight",
        ),
        migrations.DeleteModel(
            name="MapsGeo",
        ),
        migrations.RenameField(
            model_name="airportweather",
            old_name="lastUpdated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="airportweather",
            name="forecastEnd",
        ),
        migrations.RemoveField(
            model_name="airportweather",
            name="forecastStart",
        ),
        migrations.RemoveField(
            model_name="airportweather",
            name="iata",
        ),
        migrations.RemoveField(
            model_name="airportweather",
            name="icao",
        ),
        migrations.RemoveField(
            model_name="airportweather",
            name="observedAt",
        ),
        migrations.AlterField(
            model_name="airportweather",
            name="key",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="airportweather",
            name="providerSource",
            field=models.CharField(
                db_index=True, default="openweathermap", max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="apirequestlog",
            index=models.Index(
                fields=["provider", "created_at"], name="ix_provider_created"
            ),
        ),
        migrations.AddIndex(
            model_name="apirequestlog",
            index=models.Index(
                fields=["provider", "endpoint"], name="ix_provider_endpoint"
            ),
        ),
    ]
