# Generated by Django 5.2.7 on 2025-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('yyyymmdd', models.CharField(db_index=True, max_length=8)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'yyyymmdd'], name='home_apiusa_provide_6ba016_idx')],
                'unique_together': {('provider', 'yyyymmdd')},
            },
        ),
    ]
    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Flight Number: (AB1234)', max_length=25)),
                ('departing_city', models.CharField(help_text='City of Departure', max_length=50)),
                ('arriving_city', models.CharField(help_text='City of Arrival', max_length=50)),
                ('scheduled_departure', models.DateTimeField(help_text='Originally scheduled departure time')),
                ('scheduled_arrival', models.DateTimeField(help_text='Originally scheduled arrival time')),
                ('estimated_departure', models.DateTimeField(blank=True, help_text='Current estimated departure time (based on weather/delays) ', null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, help_text='Current estimated arrival time (based on weather/delays) ', null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='When flight record was created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated')),
            ],
            options={
                'ordering': ['scheduled_departure'],
            },
        ),
    ]
