# Generated by Django 5.2.7 on 2025-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('yyyymmdd', models.CharField(db_index=True, max_length=8)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'yyyymmdd'], name='home_apiusa_provide_6ba016_idx')],
                'unique_together': {('provider', 'yyyymmdd')},
            },
        ),
    ]
