# Generated by Django 5.0.14 on 2025-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=40)),
                ("yyyymmdd", models.CharField(db_index=True, max_length=8)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "yyyymmdd"],
                        name="home_apiusa_provide_6ba016_idx",
                    )
                ],
                "unique_together": {("provider", "yyyymmdd")},
            },
        ),
    ]
