# Generated by Django 5.0.14 on 2025-11-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(help_text='Airport code (e.g., DEN, LAX)', max_length=10)),
                ('airport_name', models.CharField(help_text='Full airport name', max_length=100)),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('heavy_rain', 'Heavy Rain'), ('snow', 'Snow'), ('thunderstorm', 'Thunderstorm'), ('fog', 'Fog'), ('wind', 'Windy')], default='clear', help_text='Current weather condition', max_length=20)),
                ('temperature', models.IntegerField(help_text='Temperature in Fahrenheit')),
                ('wind_speed', models.IntegerField(default=0, help_text='Wind speed in mph')),
                ('visibility', models.FloatField(default=10.0, help_text='Visibility in miles')),
                ('precipitation_chance', models.IntegerField(default=0, help_text='Chance of precipitation (0-100%)')),
                ('delay_risk', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('severe', 'Severe Risk')], default='low', help_text='Predicted delay risk level', max_length=20)),
                ('delay_probability', models.IntegerField(default=0, help_text='Probability of delays (0-100%)')),
                ('estimated_delay_minutes', models.IntegerField(default=0, help_text='Estimated delay in minutes')),
                ('forecast_time', models.DateTimeField(help_text='Time this forecast is for')),
                ('forecast_description', models.TextField(blank=True, help_text='Detailed forecast description')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time weather data was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this weather record was created')),
            ],
            options={
                'ordering': ['forecast_time'],
                'unique_together': {('airport_code', 'forecast_time')},
            },
        ),
    ]
