# Generated by Django 5.0.7 on 2025-12-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_airportweather'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='TrackedFlight',
        ),
        migrations.AddField(
            model_name='trackedflight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
