# Generated by Django 5.2.7 on 2025-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=3)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=3)),
                ('destination_city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('airborne', 'Airborne'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('on-time', 'On Time')], max_length=20)),
                ('scheduled_departure', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.CharField(blank=True, max_length=50)),
                ('gate', models.CharField(blank=True, max_length=10)),
                ('terminal', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_departure'],
                'indexes': [models.Index(fields=['flight_number'], name='search_flig_flight__2d684c_idx'), models.Index(fields=['airline'], name='search_flig_airline_8c36ee_idx'), models.Index(fields=['origin', 'destination'], name='search_flig_origin_39afb1_idx'), models.Index(fields=['status'], name='search_flig_status_dc8a68_idx')],
            },
        ),
    ]
